Traceback (most recent call last):
  File "C:\Users\lenna\miniconda3\envs\jupyterbook\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\lenna\miniconda3\envs\jupyterbook\lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\lenna\miniconda3\envs\jupyterbook\lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\lenna\miniconda3\envs\jupyterbook\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\lenna\miniconda3\envs\jupyterbook\lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\lenna\miniconda3\envs\jupyterbook\lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\lenna\miniconda3\envs\jupyterbook\lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

# Load the data files
traffic_violations = pd.read_csv('../resources/traffic_violations_filtered.csv')
us_accidents = pd.read_csv('../resources/us_accidents_filtered_rows.csv')

traffic_violations['Accident'] = traffic_violations['Accident'].map({'Yes': 1, 'No': 0})
traffic_violations['Belts'] = traffic_violations['Belts'].map({'Yes': 1, 'No': 0})
traffic_violations['Personal Injury'] = traffic_violations['Personal Injury'].map({'Yes': 1, 'No': 0})
traffic_violations['Fatal'] = traffic_violations['Fatal'].map({'Yes': 1, 'No': 0})
traffic_violations['Alcohol'] = traffic_violations['Alcohol'].map({'Yes': 1, 'No': 0})
traffic_violations['Work Zone'] = traffic_violations['Work Zone'].map({'Yes': 1, 'No': 0})
traffic_violations['Contributed To Accident'] = traffic_violations['Contributed To Accident'].map({'Yes': 1, 'No': 0})

us_accidents['Astronomical_Twilight'] = us_accidents['Astronomical_Twilight'].map({'Day' : 1, 'Night' : 0})
us_accidents['Civil_Twilight'] = us_accidents['Civil_Twilight'].map({'Day' : 1, 'Night' : 0})
us_accidents['Nautical_Twilight'] = us_accidents['Nautical_Twilight'].map({'Day' : 1, 'Night' : 0})

# Convert date columns to datetime
date_format = '%Y-%m-%d'
us_accidents['Start_Time'] = pd.to_datetime(us_accidents['Start_Time'], format= "%Y-%m-%d %H:%M:%S")
traffic_violations['Date Of Stop'] = pd.to_datetime(traffic_violations['Date Of Stop'], format= date_format)

# Extract date parts for aggregation
us_accidents['Date'] = us_accidents['Start_Time'].dt.date
traffic_violations['Date'] = traffic_violations['Date Of Stop'].dt.date

# Aggregate data by date and state
us_accidents_agg = us_accidents.groupby(['Date']).agg({
    'Severity': 'mean', 
    'Distance(mi)': 'sum'
}).reset_index()

traffic_violations_agg = traffic_violations.groupby(['Date', 'State']).agg({
    'Accident': 'sum',
    'Belts': 'sum',
    'Personal Injury': 'sum',
    'Fatal': 'sum',
    'Alcohol': 'sum',
    'Work Zone': 'sum',
    'Contributed To Accident': 'sum'
}).reset_index()

# Merge datasets on date
merged_data = pd.merge(us_accidents_agg, traffic_violations_agg, on='Date', how='inner')

# Compute correlation matrix
correlation_matrix = merged_data.corr(numeric_only= True)

correlation_matrix

------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[1], line 1[0m
[1;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m
[0;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m
[0;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01mseaborn[39;00m [38;5;28;01mas[39;00m [38;5;21;01msns[39;00m

[1;31mModuleNotFoundError[0m: No module named 'pandas'

